runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/frontend-angular/index.html
  upload: dist/frontend-angular/index.html

- url: /
  static_dir: dist/frontend-angular